export const jobs = [
  {
    jobId: 1,
    jobTitle: "Frontend Developer",
    company: "Google",
    about: "Build responsive UI components with React and modern JavaScript frameworks.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Entry Level",
    time: "2025-09-23T14:30:00",
    salary: 655555,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 2,
    jobTitle: "Backend Engineer",
    company: "Microsoft",
    about: "Develop REST APIs and optimize server-side logic for large-scale applications.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T14:35:00",
    salary: 60000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 3,
    jobTitle: "UI/UX Designer",
    company: "Adobe",
    about: "Design intuitive interfaces and create seamless user experiences for web apps.",
    location: "Remote",
    type: "Freelancing",
    level: "Intermediate",
    time: "2025-09-23T14:40:00",
    salary: 65900000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 4,
    jobTitle: "Data Analyst",
    company: "Netflix",
    about: "Analyze user behavior data and provide insights for content strategies.",
    location: "Pune",
    type: "Part-Time",
    level: "Entry Level",
    time: "2025-09-23T14:45:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 5,
    jobTitle: "Full Stack Developer",
    company: "Apple",
    about: "Work on both frontend and backend, deploy scalable web applications.",
    location: "Delhi",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T14:50:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 6,
    jobTitle: "DevOps Engineer",
    company: "Meta",
    about: "Maintain CI/CD pipelines, cloud infrastructure, and deployment automation.",
    location: "Chennai",
    type: "Internship",
    level: "Intermediate",
    time: "2025-09-23T14:55:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 7,
    jobTitle: "Cloud Architect",
    company: "Google",
    about: "Design scalable cloud infrastructure with GCP services.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T15:00:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 8,
    jobTitle: "Machine Learning Engineer",
    company: "Microsoft",
    about: "Build and optimize machine learning models for production use.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T15:05:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 9,
    jobTitle: "Graphic Designer",
    company: "Adobe",
    about: "Create design assets for digital marketing campaigns and products.",
    location: "Remote",
    type: "Freelancing",
    level: "Entry Level",
    time: "2025-09-23T15:10:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 10,
    jobTitle: "Data Scientist",
    company: "Netflix",
    about: "Develop models to recommend content and optimize streaming.",
    location: "Mumbai",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T15:15:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 11,
    jobTitle: "iOS Developer",
    company: "Apple",
    about: "Develop applications for the iOS ecosystem.",
    location: "Delhi",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T15:20:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 12,
    jobTitle: "Research Scientist",
    company: "Meta",
    about: "Conduct research in AI and AR/VR technologies.",
    location: "Remote",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T15:25:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 13,
    jobTitle: "Android Developer",
    company: "Google",
    about: "Develop Android apps with Kotlin and modern frameworks.",
    location: "Pune",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T15:30:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 14,
    jobTitle: "System Engineer",
    company: "Microsoft",
    about: "Support system architecture and software integration.",
    location: "Chennai",
    type: "Part-Time",
    level: "Entry Level",
    time: "2025-09-23T15:35:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 15,
    jobTitle: "Product Designer",
    company: "Adobe",
    about: "Work with product teams to design user-centric interfaces.",
    location: "Remote",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T15:40:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 16,
    jobTitle: "Content Analyst",
    company: "Netflix",
    about: "Analyze content performance and recommend new trends.",
    location: "Bangalore",
    type: "Part-Time",
    level: "Entry Level",
    time: "2025-09-23T15:45:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 17,
    jobTitle: "Security Engineer",
    company: "Apple",
    about: "Protect applications and systems from vulnerabilities.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T15:50:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 18,
    jobTitle: "AI Engineer",
    company: "Meta",
    about: "Develop generative AI solutions for social platforms.",
    location: "Delhi",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T15:55:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 19,
    jobTitle: "Web Developer",
    company: "Google",
    about: "Build scalable and secure websites using modern technologies.",
    location: "Chennai",
    type: "Full-Time",
    level: "Entry Level",
    time: "2025-09-23T16:00:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 20,
    jobTitle: "Software Engineer",
    company: "Microsoft",
    about: "Work on scalable backend systems and enterprise tools.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T16:05:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 21,
    jobTitle: "Illustrator",
    company: "Adobe",
    about: "Create custom illustrations and visual designs for digital platforms.",
    location: "Remote",
    type: "Freelancing",
    level: "Entry Level",
    time: "2025-09-23T16:10:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 22,
    jobTitle: "Streaming Engineer",
    company: "Netflix",
    about: "Improve video streaming quality and optimize CDN distribution.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T16:15:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 23,
    jobTitle: "Hardware Engineer",
    company: "Apple",
    about: "Design and test hardware components for devices.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T16:20:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 24,
    jobTitle: "AR/VR Developer",
    company: "Meta",
    about: "Build immersive AR/VR applications and frameworks.",
    location: "Remote",
    type: "Internship",
    level: "Entry Level",
    time: "2025-09-23T16:25:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 25,
    jobTitle: "Technical Writer",
    company: "Google",
    about: "Prepare clear documentation, API guides, and product manuals.",
    location: "Pune",
    type: "Freelancing",
    level: "Intermediate",
    time: "2025-09-23T16:30:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 26,
    jobTitle: "Database Administrator",
    company: "Microsoft",
    about: "Manage and optimize large-scale SQL and NoSQL databases.",
    location: "Delhi",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T16:35:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 27,
    jobTitle: "UX Researcher",
    company: "Adobe",
    about: "Conduct usability tests and user research for product improvements.",
    location: "Chennai",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T16:40:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 28,
    jobTitle: "Recommendation Systems Engineer",
    company: "Netflix",
    about: "Develop algorithms for personalized content recommendations.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T16:45:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 29,
    jobTitle: "QA Engineer",
    company: "Apple",
    about: "Automate testing processes and ensure high-quality software releases.",
    location: "Remote",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T16:50:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 30,
    jobTitle: "Network Engineer",
    company: "Meta",
    about: "Manage data center networks and optimize performance.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T16:55:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 31,
    jobTitle: "Cloud Engineer",
    company: "Google",
    about: "Deploy and maintain scalable cloud-native applications.",
    location: "Delhi",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T17:00:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 32,
    jobTitle: "Game Developer",
    company: "Microsoft",
    about: "Build interactive game experiences for Xbox and PC.",
    location: "Remote",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T17:05:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 33,
    jobTitle: "Animation Artist",
    company: "Adobe",
    about: "Create engaging animations for digital media.",
    location: "Pune",
    type: "Freelancing",
    level: "Entry Level",
    time: "2025-09-23T17:10:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 34,
    jobTitle: "Content Strategist",
    company: "Netflix",
    about: "Plan and manage digital content strategy across regions.",
    location: "Delhi",
    type: "Part-Time",
    level: "Intermediate",
    time: "2025-09-23T17:15:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 35,
    jobTitle: "Embedded Systems Engineer",
    company: "Apple",
    about: "Develop firmware and embedded systems for devices.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T17:20:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 36,
    jobTitle: "Mobile QA Tester",
    company: "Meta",
    about: "Test mobile applications on various platforms.",
    location: "Chennai",
    type: "Internship",
    level: "Entry Level",
    time: "2025-09-23T17:25:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 37,
    jobTitle: "Technical Support Engineer",
    company: "Google",
    about: "Provide technical support for cloud services.",
    location: "Remote",
    type: "Full-Time",
    level: "Entry Level",
    time: "2025-09-23T17:30:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 38,
    jobTitle: "Big Data Engineer",
    company: "Microsoft",
    about: "Build pipelines for processing large data sets.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T17:35:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 39,
    jobTitle: "Digital Marketing Specialist",
    company: "Adobe",
    about: "Plan and execute digital marketing campaigns.",
    location: "Delhi",
    type: "Part-Time",
    level: "Intermediate",
    time: "2025-09-23T17:40:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 40,
    jobTitle: "Technical Recruiter",
    company: "Netflix",
    about: "Identify and hire top engineering talent.",
    location: "Pune",
    type: "Full-Time",
    level: "Entry Level",
    time: "2025-09-23T17:45:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 41,
    jobTitle: "System Administrator",
    company: "Apple",
    about: "Maintain servers and IT infrastructure.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T17:50:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 42,
    jobTitle: "Software Architect",
    company: "Meta",
    about: "Design software architecture for large-scale systems.",
    location: "Remote",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T17:55:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 43,
    jobTitle: "QA Lead",
    company: "Google",
    about: "Lead quality assurance teams and manage testing strategies.",
    location: "Chennai",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T18:00:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 44,
    jobTitle: "DevOps Manager",
    company: "Microsoft",
    about: "Oversee DevOps teams and deployment processes.",
    location: "Delhi",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T18:05:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 45,
    jobTitle: "Graphic Artist",
    company: "Adobe",
    about: "Design graphics for marketing and branding.",
    location: "Remote",
    type: "Freelancing",
    level: "Entry Level",
    time: "2025-09-23T18:10:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 46,
    jobTitle: "AI Researcher",
    company: "Netflix",
    about: "Research cutting-edge AI technologies.",
    location: "Hyderabad",
    type: "Full-Time",
    level: "Expert",
    time: "2025-09-23T18:15:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 47,
    jobTitle: "Mobile Developer",
    company: "Apple",
    about: "Develop apps for both iOS and Android platforms.",
    location: "Bangalore",
    type: "Full-Time",
    level: "Intermediate",
    time: "2025-09-23T18:20:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  },
  {
    jobId: 48,
    jobTitle: "Customer Success Manager",
    company: "Meta",
    about: "Manage client relationships and support business growth.",
    location: "Delhi",
    type: "Full-Time",
    level: "Entry Level",
    time: "2025-09-23T18:25:00",
    salary: 600000,
    skills: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
  }
];


